arch: Unet
batch_size: 8
decoder_dropout: 0.2
device: !!python/object/apply:torch.device
- mps
encoder_name: efficientnet-b3
encoder_weights: imagenet
in_channels: 3
learning_rate: 0.001
max_epochs: 10
out_classes: 7
